"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var SessionKeys;
(function (SessionKeys) {
    SessionKeys["SignInInfo"] = "signin_info";
    SessionKeys["AccessToken"] = "access_token";
    SessionKeys["ExpiresIn"] = "expires_in";
    SessionKeys["RefreshToken"] = "refresh_token";
    SessionKeys["TokenType"] = "token_type";
    SessionKeys["AdminPermissions"] = "admin_permissions";
    SessionKeys["CompanyNumber"] = "company_number";
    SessionKeys["SignedIn"] = "signed_in";
    SessionKeys["UserProfile"] = "user_profile";
    SessionKeys["Email"] = "email";
    SessionKeys["Forename"] = "forename";
    SessionKeys["Surname"] = "surname";
    SessionKeys["UserId"] = "id";
    SessionKeys["Locale"] = "locale";
    SessionKeys["Permissions"] = "permissions";
    SessionKeys["Scope"] = "scope";
    SessionKeys["ClientSig"] = ".client.signature";
    SessionKeys["Expires"] = "expires";
    SessionKeys["Id"] = ".id";
    SessionKeys["LastAccess"] = "last_access";
    SessionKeys["ChangingDetails"] = "checking_details";
    SessionKeys["extensionReasons"] = "extension_reasons";
    SessionKeys["ExtensionRequests"] = "extension_requests";
    SessionKeys["Extension_Session"] = "extension_session";
    SessionKeys["CompanyInContext"] = "company_in_context";
    SessionKeys["PageHistory"] = "page_history";
    SessionKeys["NavigationBackFlag"] = "back_button_pressed";
    SessionKeys["UploadDocumentsYes"] = "upload_documents_yes";
    SessionKeys["UploadDocumentsNo"] = "upload_documents_no";
    SessionKeys["AddAnotherReasonYes"] = "add_another_reason_yes";
    SessionKeys["AddAnotherReasonNo"] = "add_another_reason_no";
    SessionKeys["AccountingIssuesChosen"] = "accounting_issues_chosen";
    SessionKeys["IllnessChosen"] = "illness_chosen";
    SessionKeys["MissingAuthenticationCodeChosen"] = "missing_company_authentication_code_chosen";
    SessionKeys["OtherChosen"] = "other_chosen";
    SessionKeys["AlreadySubmitted"] = "already_submitted";
    SessionKeys["ExtraData"] = "extra_data";
    SessionKeys["SessionId"] = "SessionId";
})(SessionKeys = exports.SessionKeys || (exports.SessionKeys = {}));
//# sourceMappingURL=SessionKeys.js.map